### PR TITLE
db service set up

### PR DESCRIPTION
**Pull request by Jephtha**

### CODE REVIEW

**Review by krp311 — CHANGES_REQUESTED** [review]
Each user's profile should store the course name and section, not just the course name In the case of multiple slots for the same course, the schedule-maker will need to know which specific section the user is in to be able to retrieve the course info from the json file. 
Alternatively: the database could store the CRN instead of the course name and section.

**Comment by Jephtha** [comment]
will store the course no& section in this format: CourseNo-section e.g (COMP4768-001) as a string in db compared to crn as not all crns are valid in our json

**Review by krp311 — APPROVED** [review]

**Comment by Jephtha** [comment]
this PR initialized user auth for this project. more work will be done on this by @b-pollett. this is simply Initialization of the task

**Comment by Jephtha** [comment]
linked PR with changes https://github.com/Jephtha/schedulink/pull/24

**Comment by Jephtha** [comment]
linked PR with changes https://github.com/Jephtha/schedulink/pull/25

**Comment by Jephtha** [comment]
> this PR initialized user auth for this project. more work will be done on this by @b-pollett. this is simply Initialization of the task

@b-pollett dropped the user auth task. will now be completed by me.

**Pull request merged**
