### PR TITLE
User Info Profile and Theme

### PR DESCRIPTION
**Pull request by A-James-Y**
The updated version of the previous branch with user info and theme fully functional.

### CODE REVIEW

**Review by Jephtha — CHANGES_REQUESTED** [review]
everything is mostly fine, i just don't approve of naming the new file courses_info when there is a course_info file already present. it's way too confusing. should change the name.

also need to change the colors of some buttons, particularly the green ones as they looked fine i light mode, but with the dark mode toggle it's really hard to read the words on them.

finally, the dark mode toggle itself is a bit tacky, simply changing the icon to something else might do the trick

**Comment by Jephtha** [comment]
changed the name & the dark mode toggle icon from switch to light & dark mode icons respectively. 
and a quality of life change unrelated to this PR was made to the alert dialogs to make them disappear after 3 seconds vs 10 as i think 10 seconds is too long.

all that is needed is the button update

**Comment by krp311** [comment]
Made some changes to how the Profile displays the users name and contact.

**Review by Jephtha — APPROVED** [review]
looks good!

**Pull request merged**
